Traceback (most recent call last):
  File "/home/runner/work/TLVSsolution/TLVSsolution/Content_prod/logics/participants.py", line 138, in <module>
    for club in tournaments[ass]['tournaments'][tourn]['participants']:
KeyError: 'participants'
