Traceback (most recent call last):
  File "/home/runner/work/TLVSsolution/TLVSsolution/Content_prod/logics/standings_finish.py", line 88, in <module>
    standings[club]['nat'], standings[club]['club_NATpos'], club_qouta) + '\n'
KeyError: 'club_NATpos'
