Traceback (most recent call last):
  File "/home/runner/work/TLVSsolution/TLVSsolution/Content_prod/logics/tournaments.py", line 108, in <module>
    with open((os.path.abspath(__file__))[:-22]+'/cache/sub_results/club_sets/'\
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/TLVSsolution/TLVSsolution/Content_prod/cache/sub_results/club_sets/UEL 2023-2024 group set.txt'
