Traceback (most recent call last):
  File "/home/runner/work/TLVSsolution/TLVSsolution/Content_prod/logics/modules/cup_round_ratings.py", line 80, in cup_round_ratings
    with open((os.path.abspath(__file__))[:-36]+'/cache/sub_results/standings_history/standings '\
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/TLVSsolution/TLVSsolution/Content_prod/cache/sub_results/standings_history/standings 2100-01-01.json'
