Traceback (most recent call last):
  File "/home/runner/work/TLVSsolution/TLVSsolution/Content_prod/logics/modules/cup_files.py", line 318, in func_cup_files
    with open((os.path.abspath(__file__))[:-28]+'/cache/answers/fixtures'+prev_find, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/TLVSsolution/TLVSsolution/Content_prod/cache/answers/fixturesENG LCup 23-24 prev.json'
